// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyTiv4nVFZlD_ixrWgjKiUwX68MLqQ9W4',
    appId: '1:434714999478:web:9d1fd705560ca014fd0417',
    messagingSenderId: '434714999478',
    projectId: 'easysooq-14a30',
    authDomain: 'easysooq-14a30.firebaseapp.com',
    storageBucket: 'easysooq-14a30.firebasestorage.app',
    measurementId: 'G-3R220YGE60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDvHFqs5VE-AMbIN-ChF8pli9OQET7IP8',
    appId: '1:434714999478:android:21ec37796839b3dbfd0417',
    messagingSenderId: '434714999478',
    projectId: 'easysooq-14a30',
    storageBucket: 'easysooq-14a30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDRXbr6i675Wv0P6Ib1wODUcDzDpF8TXs',
    appId: '1:434714999478:ios:3b158e6e07ed9b61fd0417',
    messagingSenderId: '434714999478',
    projectId: 'easysooq-14a30',
    storageBucket: 'easysooq-14a30.firebasestorage.app',
    iosBundleId: 'com.sixamtech.grofresh',
  );
}
